# Generated by Django 4.2.8 on 2023-12-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('timeStart', models.DateField()),
                ('timeEnd', models.DateField()),
                ('itsEnd', models.BooleanField(default=False)),
            ],
        ),
    ]
