# Generated by Django 4.2.8 on 2023-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('units', models.CharField(max_length=250)),
                ('types', models.CharField(choices=[('material', 'Material'), ('service', 'Service')], default='material', max_length=20)),
            ],
        ),
    ]
